import mimetypes
import os
from io import BytesIO
from typing import List, Set

from cat.log import log
from cat.services.memory.models import Record, VectorMemoryType
from cat.utils import guess_file_type

DECLARATIVE = str(VectorMemoryType.DECLARATIVE)


def _is_root_file(path: str, name: str, agent_key: str) -> bool:
    """Whether the file lives directly in the folder of the agent (the datalake), not in the folder of a chat."""
    if not name or "/" in name or name.startswith("."):
        return False
    normalized = path.replace(os.sep, "/")
    marker = f"{agent_key}/"
    if marker not in normalized:
        return True
    relative = normalized.split(marker, 1)[1]
    return "/" not in relative


async def get_derived_files(ccat) -> Set[str]:
    """Names of the files derived from an ingestion (e.g. the images extracted by the multimodal ingestion), which are
    stored next to the uploaded files but are not part of the datalake."""
    points, _ = await ccat.vector_memory_handler.get_all_tenant_points(DECLARATIVE, with_vectors=False)
    derived = set()
    for point in points:
        metadata = (point.payload or {}).get("metadata") or {}
        if image_file := metadata.get("image_file"):
            if image_file != metadata.get("source"):
                derived.add(os.path.basename(str(image_file)))
    return derived


async def list_datalake_files(ccat) -> List[str]:
    """The datalake of the Cheshire Cat: the files stored by its file manager in the folder of the agent (the files of
    the conversations, stored in the sub-folders of the chats, are excluded), sorted by name."""
    agent_key = ccat.agent_key
    files = ccat.file_manager.list_files(agent_key)
    derived = await get_derived_files(ccat)

    names = {
        f.name for f in files
        if _is_root_file(f.path, f.name, agent_key) and f.name not in derived
    }
    return sorted(names)


def read_datalake_file(ccat, name: str) -> bytes | None:
    try:
        return ccat.file_manager.read_file(name, ccat.agent_key)
    except Exception as e:
        log.warning(f"AutoChunk: unable to read {name} from the file manager of agent {ccat.agent_key}: {e}")
        return None


def guess_content_type(name: str, content: bytes) -> str | None:
    content_type, _ = guess_file_type(BytesIO(content))
    if content_type in (None, "text/plain"):
        # the extension is more specific for the text formats (markdown, csv, json, html...)
        by_extension, _ = mimetypes.guess_type(name)
        content_type = by_extension or content_type
    return content_type


async def get_source_points(ccat, name: str) -> List[Record]:
    """The points of the declarative memory generated by the ingestion of a datalake file.

    Only the points of the declarative memory whose source is the file are returned, excluding the ones of any chat
    (they belong to the episodic memory anyway): every other point of the vector database is out of scope.
    """
    points, _ = await ccat.vector_memory_handler.get_all_tenant_points(
        DECLARATIVE, metadata={"source": name}, with_vectors=False,
    )
    return [
        p for p in points
        if ((p.payload or {}).get("metadata") or {}).get("source") == name
        and not ((p.payload or {}).get("metadata") or {}).get("chat_id")
    ]
