"""The ingestion steps of the Cheshire Cat (RabbitHole), reproduced with an explicit chunker.

The optimization evaluates many chunkers without touching the active one (``cat.chunker``), which keeps serving the
ingestions running meanwhile: the parsing and the splitting are reproduced here as the RabbitHole does them, hooks
included, with the chunker under evaluation.
"""
import copy
import hashlib
import json
from dataclasses import dataclass
from typing import Any, Dict, List

from langchain_core.documents import Document
from langchain_core.documents.base import Blob

from cat.core_plugins.base_plugin.parsers import MimeTypeBasedParser
from cat.log import log
from cat.services.factory.chunker import BaseChunker

from .datalake import DECLARATIVE, get_source_points, guess_content_type, read_datalake_file

# metadata set by the core on every chunk (or by the vector database): never carried over by the re-ingestion, they
# are generated again
RESERVED_METADATA_KEYS = {
    "source", "when", "hash", "chat_id", "tenant_id", "id", "image_file", "_merge_count", "_is_merged",
}


async def parse_file(ccat, name: str, content: bytes, content_type: str | None) -> List[Document]:
    """Parse a file into LangChain documents, without splitting them (as ``RabbitHole._parse_to_docs`` does)."""
    handlers = await ccat.file_handlers()

    def parse():
        blob = Blob(data=content, mimetype=content_type).from_data(data=content, mime_type=content_type, path=name)
        return MimeTypeBasedParser(handlers=handlers).parse(blob)

    docs = await ccat._run_in_ingestion_executor(parse)
    for doc in docs:
        if isinstance(doc.metadata, dict):
            doc.metadata.setdefault("source", name)
            # transient payload of the multimodal parsers: not needed to evaluate the text chunking
            doc.metadata.pop("image_base64", None)
    return [d for d in docs if d.page_content and d.page_content.strip()]


async def split_with_chunker(ccat, chunker: BaseChunker, docs: List[Document]) -> List[Document]:
    """Split the documents with the given chunker, as ``RabbitHole._split_text`` does with the active chunker."""
    plugin_manager = ccat.plugin_manager

    docs = await plugin_manager.execute_hook("before_rabbithole_splits_documents", docs, caller=ccat)
    docs = await chunker.split_documents(docs)

    try:
        docs = ccat.rabbit_hole._merge_short_chunks(docs, chunker)
    except Exception as e:
        log.debug(f"AutoChunk: error merging short chunks: {e}. Proceeding with original chunks.")

    try:
        docs = await plugin_manager.execute_hook("finalize_oversized_chunks", docs, caller=ccat)
    except Exception as e:
        log.debug(f"AutoChunk: failed to finalize oversized chunks: {e}. Proceeding with original chunks.")

    return [d for d in docs if d.page_content and d.page_content.strip()]


def _freeze(value: Any) -> str:
    return json.dumps(value, sort_keys=True, default=str)


def extract_custom_metadata(old_points: List[Any], generated_keys: set) -> Dict[str, Any]:
    """The metadata given at upload time to a file (e.g. through the ``metadata`` field of the upload endpoint).

    They are stored on every chunk of the file, so they are the metadata with the same value in every text point of
    the file; the ones set by the core or generated by the parsers/chunkers are excluded.
    """
    text_metadata = [
        (p.payload or {}).get("metadata") or {}
        for p in old_points
        if not ((p.payload or {}).get("metadata") or {}).get("image_file")
    ] or [(p.payload or {}).get("metadata") or {} for p in old_points]
    if not text_metadata:
        return {}

    common = dict(text_metadata[0])
    for metadata in text_metadata[1:]:
        common = {k: v for k, v in common.items() if k in metadata and _freeze(metadata[k]) == _freeze(v)}

    return {k: v for k, v in common.items() if k not in RESERVED_METADATA_KEYS and k not in generated_keys}


@dataclass
class ReinjectionOutcome:
    name: str
    success: bool
    old_points: int = 0
    new_points: int = 0
    error: str | None = None

    def as_dict(self) -> Dict[str, Any]:
        return {
            "name": self.name,
            "success": self.success,
            "old_points": self.old_points,
            "new_points": self.new_points,
            "error": self.error,
        }


async def reinject_file(ccat, name: str) -> ReinjectionOutcome:
    """Re-ingest a datalake file with the active chunker of the Cheshire Cat, safely.

    The new points are stored BEFORE the old ones of the file are deleted, and the old ones are deleted by id: if
    anything goes wrong, the file keeps its old points. Only the points of the file are touched: every other point of
    the vector database (other sources, URLs, memories uploaded without a file, chats...) is left as it is. The custom
    metadata given at upload time are carried over to the new points.
    """
    content = read_datalake_file(ccat, name)
    if not content:
        return ReinjectionOutcome(name=name, success=False, error="unable to read the file from the file manager")

    old_points = await get_source_points(ccat, name)
    content_type = guess_content_type(name, content)

    try:
        # a copy of the shared RabbitHole, bound to this cat, as RabbitHole.ingest_file does
        rabbit_hole = copy.copy(ccat.rabbit_hole)
        await rabbit_hole.setup(ccat)

        docs, images = await rabbit_hole._parse_to_docs(name, content, content_type)
        if not docs:
            return ReinjectionOutcome(name=name, success=False, old_points=len(old_points), error="no valid chunks")

        generated_keys = {k for d in docs for k in (d.metadata or {})}
        metadata = extract_custom_metadata(old_points, generated_keys)

        new_points = await rabbit_hole.store_documents(
            docs=docs,
            source=name,
            file_hash=hashlib.sha256(content).hexdigest(),
            metadata=metadata,
            images=images,
            source_bytes=content,
        )
    except Exception as e:
        log.error(f"AutoChunk: re-ingestion of {name} failed, its old points are kept: {e}")
        return ReinjectionOutcome(name=name, success=False, old_points=len(old_points), error=str(e))

    if not new_points:
        return ReinjectionOutcome(name=name, success=False, old_points=len(old_points), error="no points stored")

    new_ids = {str(p.id) for p in new_points}
    stale_ids = [p.id for p in old_points if str(p.id) not in new_ids]
    if stale_ids:
        try:
            await ccat.vector_memory_handler.delete_tenant_points_by_ids(DECLARATIVE, stale_ids)
        except Exception as e:
            # the file is duplicated until the next run, which deletes every old point of the file again
            log.error(f"AutoChunk: unable to delete the old points of {name}: {e}")
            return ReinjectionOutcome(
                name=name, success=False, old_points=len(old_points), new_points=len(new_points),
                error=f"new points stored, old points not deleted: {e}",
            )

    return ReinjectionOutcome(name=name, success=True, old_points=len(old_points), new_points=len(new_points))
