from typing import Any, Dict, List

from pydantic import BaseModel, Field, field_validator

from cat import plugin

from .cron import parse_cron_expression


class AutoChunkSettings(BaseModel):
    """Settings of the AutoChunk plugin, stored per Cheshire Cat (agent)."""

    # --- scheduling -------------------------------------------------------------------------------------------------
    enabled: bool = Field(
        default=True,
        description="Whether the scheduled optimization + re-ingestion is active for this Cheshire Cat.",
    )
    cron_expression: str = Field(
        default="0 3 * * 0",
        description="Standard 5-field cron expression (minute hour day-of-month month day-of-week), in UTC, used by "
                    "White Rabbit to schedule the job. Default: every Sunday at 03:00 UTC.",
    )

    # --- optimizer (pyVolutionary) ----------------------------------------------------------------------------------
    algorithm: str = Field(
        default="GreyWolfOptimization",
        description="Name of the pyVolutionary optimization class (e.g. GreyWolfOptimization, "
                    "ParticleSwarmOptimization, GeneticAlgorithmOptimization, WhalesOptimization).",
    )
    algorithm_parameters: Dict[str, Any] = Field(
        default_factory=dict,
        description="Extra parameters of the algorithm configuration (e.g. {\"c1\": 0.1, \"c2\": 0.1, \"w\": [0.35, 1]} "
                    "for ParticleSwarmOptimization). population_size and max_cycles are set by the fields below.",
    )
    population_size: int = Field(
        default=8,
        ge=2,
        description="Number of agents of the population. Some algorithms need more agents (e.g. 3 for "
                    "GreyWolfOptimization, 4 for BeeColonyOptimization): pyVolutionary reports the minimum.",
    )
    max_cycles: int = Field(default=6, ge=1, description="Maximum number of generations of the optimizer.")
    max_evaluations: int = Field(
        default=60,
        ge=1,
        description="Maximum number of distinct chunker configurations evaluated in a run (the expensive part: each "
                    "one re-chunks and re-embeds the sample). Further candidates get the worst fitness.",
    )
    max_runtime_minutes: int = Field(
        default=120,
        ge=1,
        description="Time budget of the optimization phase. Once exceeded, further candidates get the worst fitness.",
    )
    seed: int | None = Field(default=None, description="Random seed, for reproducible runs.")

    # --- search space ----------------------------------------------------------------------------------------------
    allowed_chunkers: List[str] = Field(
        default_factory=list,
        description="Names of the chunker settings classes to consider (e.g. RecursiveTextChunkerSettings). "
                    "Empty: every chunker available to this Cheshire Cat.",
    )
    search_space_overrides: Dict[str, Dict[str, Any]] = Field(
        default_factory=dict,
        description="Per-parameter overrides of the search space, keyed by \"<ChunkerSettingsClass>.<field>\". "
                    "Values: {\"min\": x, \"max\": y} for numbers, {\"choices\": [...]} for a discrete set, "
                    "{\"fixed\": value} to exclude the parameter from the optimization.",
    )

    # --- fitness ---------------------------------------------------------------------------------------------------
    sample_max_files: int = Field(
        default=10, ge=1, description="Maximum number of datalake files sampled to evaluate the chunkers."
    )
    sample_max_chars_per_file: int = Field(
        default=200_000, ge=1_000, description="Files are truncated to this number of characters for the evaluation."
    )
    questions_per_file: int = Field(
        default=3, ge=1, description="Synthetic questions generated by the LLM for every sampled file."
    )
    min_questions: int = Field(
        default=5,
        ge=1,
        description="Minimum number of valid synthetic questions: below it, the run is aborted and nothing changes.",
    )
    top_k: int = Field(default=5, ge=1, description="k of the retrieval metrics (MRR@k).")
    size_penalty: float = Field(
        default=0.05,
        ge=0.0,
        description="Penalty on the average chunk size (per 1000 tokens), subtracted from MRR@k: it keeps the "
                    "optimizer from preferring huge chunks, which are costly in the LLM context.",
    )
    min_improvement: float = Field(
        default=0.02,
        ge=0.0,
        description="Minimum fitness gain over the current chunker needed to switch to the new one.",
    )

    # --- concurrency -----------------------------------------------------------------------------------------------
    lock_ttl_minutes: int = Field(
        default=720,
        ge=10,
        description="Expiration of the per-agent lock preventing concurrent runs on several workers.",
    )

    @field_validator("cron_expression")
    @classmethod
    def validate_cron_expression(cls, v: str) -> str:
        parse_cron_expression(v)
        return v.strip()

    @field_validator("algorithm")
    @classmethod
    def validate_algorithm(cls, v: str) -> str:
        v = v.strip()
        if not v:
            raise ValueError("The algorithm cannot be empty")
        return v


@plugin
def settings_model():
    return AutoChunkSettings
